### PR TITLE
Adaptive lighting fix

### PR DESCRIPTION
**Pull request by arlogilbert**
Addresses #101 and #126 by checking if switch status is on in the .groovy code before allowing the setColorTemperature command to send

### CODE REVIEW

**Comment by arlogilbert** [comment]
@tonesto7 3 changes here:

1.  was addition of code in homebridge-v2.groovy on line 1112
2. adding Visual Studio code-workspace to .gitignore
3. Increasing version to 2513

```
        if (command == "setColorTemperature" && device.currentValue("switch") != "on"){
            return CommandReply(shw, sSUCC, 'Command was setColorTemperature but device is not on', 200)
        }
```

**Comment by tonesto7** [comment]
I'm going to just handle this in the plugin if I can to eliminate a request to HE alltogether

**Comment by arlogilbert** [comment]
> I'm going to just handle this in the plugin if I can to eliminate a request to HE alltogether

I use a few apps in Hubitat such as the Mirror Me and Switch Bindings. Usual response time is < 500ms from when I press the switch off to when the command is issued to the bulbs. On occasion I've pressed the button and then the logs reflect that the button press was seen and then the setColorTemperature was received from HomeBridge maybe 20ms later which results in the off command being overridden by the setColorTemperature command.

If you rely upon the Homebridge plugin, you'll need to rely upon knowledge of the Hubitat switch state which might be another X milliseconds in addition and could result in:

1. Physical off switch pressed
2. Hubitat sees zwave or zigbee signal of status, updates it's internal DB
3. Hubitat notifies your groovy plugin
4. Your groovy plugin notifies HomeBridge plugin
5. Homebridge stops sending setColorTemperature events

I guess my (not enough coffee this AM) point is that between the time that step 2 and step 5 occur, the HomeBridge plugin may still send setColorTemperature events which leaves the issue out there.

My 2 cents is that the more solid solution is to have the logic in both places to reduce the likelihood that a color level command is sent while the two systems are briefly out of sync. The reason I think it's a better approach is that colorTemp commands are send so frequently that the chances of an out-of-sync collision are reasonably high.

**Comment by tonesto7** [comment]
I've made the changes and pushed out to public.

**Pull request closed without merging**
